"""new fields in user model

Revision ID: 898a1a038a1e
Revises: ebccf0cfcc0c
Create Date: 2017-12-22 10:40:14.750019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898a1a038a1e'
down_revision = 'ebccf0cfcc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
